=== NVIDIA-AI-IOT/inference_builder/builder/samples/tao/evaluation/coco_prediction_format.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "examples": [
      [
        {
            "image_id": 1,
            "bbox": [366.95068359, 386.24633789, 17.97363281, 17.46826172],
            "score": 0.9428234,
            "category_id": 2
        },
        {
            "image_id": 1,
            "bbox": [548.27636719, 32.32040405, 5.94726562, 5.95733643],
            "score": 0.93891287,
            "category_id": 2
        }
      ]
    ],
    "items": {
      "type": "object",
      "properties": {
        "image_id": {
          "type": "integer",
          "description": "Image identifier from source_id"
        },
        "bbox": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 4,
          "maxItems": 4,
          "description": "Bounding box coordinates [x, y, w, h] from detection_boxes"
        },
        "score": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "description": "Detection confidence score from detection_scores"
        },
        "category_id": {
          "type": "integer",
          "description": "Category identifier from detection_classes"
        }
      },
      "required": ["image_id", "bbox", "score", "category_id"]
    }
  }

=== NVIDIA-AI-IOT/inference_builder/builder/samples/tao/evaluation/coco_predictions.test.json
[
  {
    "image_id": 1,
    "bbox": [
      272.0,
      236.0,
      28.0,
      25.0
    ],
    "score": 0.5399537086486816,
    "category_id": 3
  },
  {
    "image_id": 1,
    "bbox": [
      202.0,
      303.0,
      54.0,
      44.0
    ],
    "score": 0.5898345112800598,
    "category_id": 3
  },
  {
    "image_id": 1,
    "bbox": [
      311.0,
      234.0,
      26.0,
      28.0
    ],
    "score": 0.6334102749824524,
    "category_id": 3
  },
  {
    "image_id": 1,
    "bbox": [
      346.0,
      296.0,
      46.0,
      52.0
    ],
    "score": 0.6566582918167114,
    "category_id": 3
  },
  {
    "image_id": 1,
    "bbox": [
      398.0,
      310.0,
      41.0,
      50.0
    ],
    "score": 0.754191517829895,
    "category_id": 3
  },
  {
    "image_id": 1,
    "bbox": [
      269.0,
      274.0,
      46.0,
      45.0
    ],
    "score": 0.7994422912597656,
    "category_id": 3
  }
]
